### ISSUE TITLE
Native support on Vrondakis doesn't work?

### ISSUE THREAD

**Issue by Zackyo** [GlorifiedPig/GlorifiedLeveling#3]
Hi!

I'm using VoidChar and other addons that is compatiable with Vrondakis Leveling System. However, how can I make Glorified be able to support addons that uses Vrondakis Leveling System?

Do I need to have Vrondakis AND this system?

Errors like these pops up on server console:
_Warning! DarkRPVar 'level' wasn't registered!_

**Comment by GlorifiedPig** [comment]
Hello. VoidCharacters is not implementing Vrondakis correctly, it's directly checking the DarkRP var instead of the function provided by them. It's probably for a general leveling system. You can make a support ticket and they can easily add support for GlorifiedLeveling.
